# Site settings
title: Simon Jockers

# Collection: Projects
collections:
  projects:
    output: true

defaults:
  - scope:
      type: projects
    values:
      layout: project

# Build settings
markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - Guardfile

gems:
  - jekyll-assets

assets:
  sources:
    - _assets/css
    - _assets/images
    - _assets/fonts

  assets:
    - ["*.eot", "*.ttf", "*.otf", "*.woff", "*.woff2"]
    - ["*.png", "*.jpg", "*.svg"]
    - ["main.css"]

  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
